// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe4TIqSeMsEoLI75wQs84GiQWDGtyvo9k',
    appId: '1:1026510332084:web:307b40e551336f81d1b7e1',
    messagingSenderId: '1026510332084',
    projectId: 'kinecare-81f52',
    authDomain: 'kinecare-81f52.firebaseapp.com',
    storageBucket: 'kinecare-81f52.firebasestorage.app',
    measurementId: 'G-HGCNLHLWWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgExPyK8BeKSyDSkMqBAlGcGHQWGOXh3g',
    appId: '1:1026510332084:android:d581d34f10824b17d1b7e1',
    messagingSenderId: '1026510332084',
    projectId: 'kinecare-81f52',
    storageBucket: 'kinecare-81f52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe4TIqSeMsEoLI75wQs84GiQWDGtyvo9k',
    appId: '1:1026510332084:ios:d581d34f10824b17d1b7e1',
    messagingSenderId: '1026510332084',
    projectId: 'kinecare-81f52',
    storageBucket: 'kinecare-81f52.firebasestorage.app',
    iosBundleId: 'fr.medidesk.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe4TIqSeMsEoLI75wQs84GiQWDGtyvo9k',
    appId: '1:1026510332084:ios:d581d34f10824b17d1b7e1',
    messagingSenderId: '1026510332084',
    projectId: 'kinecare-81f52',
    storageBucket: 'kinecare-81f52.firebasestorage.app',
    iosBundleId: 'fr.medidesk.demo',
  );
}
